name: flutter_lab
description: Flutter lab project

publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.4
  flutter: '>=3.38.5 <4.0.0'

dependencies:
  app_links: ^6.4.1
  applovin_max: ^4.5.0
  auto_mappr_annotation: ^2.3.0
  cached_network_image: ^3.4.1
  camera: ^0.11.3
  characters: ^1.4.0
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.5
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_form_builder: ^10.3.0
  flutter_hooks: ^0.21.3
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.4
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  go_router: ^16.1.0
  google_fonts: ^6.3.0
  google_mlkit_text_recognition: ^0.14.0
  hooks_riverpod: ^3.0.0-dev.17
  http: ^1.5.0
  http_mock_adapter: ^0.6.1
  in_app_review: ^2.0.11
  intl: any
  json_annotation: ^4.9.0
  logging: ^1.3.0
  screen_protector: ^1.5.1
  path: ^1.9.1
  path_provider: ^2.1.5
  petstore:
    path: package/petstore
  provider: ^6.1.5
  result_dart: ^2.1.1
  screen_brightness: ^2.1.7
  retrofit: ^4.7.3
  riverpod_annotation: ^3.0.0-dev.17
  share_plus: ^11.1.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  vector_graphics: ^1.1.19
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  vector_graphics_compiler: ^1.1.18
  custom_lint: ^0.8.0
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17
  flutter_gen: ^5.11.0
  very_good_analysis: ^9.0.0
  test: ^1.25.15
  mocktail: ^1.0.4
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  flutter_test:
    sdk: flutter
  auto_mappr: ^2.10.0
  retrofit_generator: ^10.0.0
  flutter_flavorizr: ^2.4.1
  go_router_builder: ^4.1.1
  build_verify: ^3.1.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  generate: true
  assets:
    - assets/
    - assets/images/
    - path: assets/icons/
      transformers:
        - package: vector_graphics_compiler
